# Generated by Django 4.2.1 on 2024-07-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1Score', models.IntegerField(default=0, verbose_name='User 1 Score')),
                ('user2Score', models.IntegerField(default=0, verbose_name='User 2 Score')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('friends', models.ManyToManyField(blank=True, to='management.user')),
                ('games', models.ManyToManyField(blank=True, related_name='players', to='management.game')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamentName', models.CharField(max_length=100)),
                ('tournamentGame', models.ManyToManyField(blank=True, related_name='tournaments', to='management.game')),
                ('tournamentUsers', models.ManyToManyField(blank=True, related_name='tournaments', to='management.user')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='management.tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_user1', to='management.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_user2', to='management.user'),
        ),
    ]
