# Generated by Django 4.2.1 on 2024-07-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
