# Generated by Django 4.2.1 on 2024-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_game_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
