# Generated by Django 4.2.1 on 2024-07-13 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_user_lose_user_nickname_user_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
