# Generated by Django 4.2.1 on 2024-07-13 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_user_friend_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
