# Generated by Django 4.2.1 on 2024-07-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_user_sent_friend_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sent_friend_requests',
        ),
    ]
