# Generated by Django 4.2.1 on 2024-07-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_delete_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_42_student',
            field=models.BooleanField(default=False),
        ),
    ]
