# Generated by Django 4.2.1 on 2024-07-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
