# Generated by Django 4.2.1 on 2024-07-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_user_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activate_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
