# Generated by Django 4.2.1 on 2024-07-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_user_reset_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
