# Generated by Django 4.2.1 on 2024-07-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_user_chat_notifications_user_friend_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('numberOfGoals', models.IntegerField(default=0)),
                ('numberOfConcededGoals', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='user',
            name='win',
        ),
        migrations.AddField(
            model_name='user',
            name='user_statistics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.userstatistics'),
        ),
    ]
