# Generated by Django 4.2.1 on 2024-07-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_userstatistics_remove_user_lose_remove_user_win_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_statistics',
        ),
        migrations.AddField(
            model_name='user',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserStatistics',
        ),
    ]
