# Generated by Django 4.2.1 on 2024-07-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_userblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_users',
        ),
    ]
