# Generated by Django 4.2.1 on 2024-07-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_game_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
