# Generated by Django 4.2.1 on 2024-07-25 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_game_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
        migrations.AddField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1Score', models.IntegerField(default=0, verbose_name='User 1 Score')),
                ('user2Score', models.IntegerField(default=0, verbose_name='User 2 Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_games', to='management.tournament')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_user1_tournament', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_user2_tournament', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
