# Generated by Django 4.2.1 on 2024-07-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_remove_game_tournament_tournament_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
