# Generated by Django 4.2.1 on 2024-07-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_alter_tournament_tournamentgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_game_invite',
            field=models.BooleanField(default=False),
        ),
    ]
