version: '3.7'

networks:
  webnet:
    name: webnet
    driver: bridge

volumes:
  postgres_data:

services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - webnet

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles
    networks:
      - webnet
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_ENGINE: django.db.backends.postgresql
