# Generated by Django 4.2.1 on 2024-07-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Game ID')),
                ('user1ID', models.IntegerField(verbose_name='User 1 ID')),
                ('user2ID', models.IntegerField(verbose_name='User 2 ID')),
                ('tournamentID', models.IntegerField(default=-1, verbose_name='Tournament ID')),
                ('user1Score', models.IntegerField(default=0, verbose_name='User 1 Score')),
                ('user2Score', models.IntegerField(default=0, verbose_name='User 2 Score')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournamentID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Tournament ID')),
                ('tournamentName', models.CharField(max_length=100)),
                ('tournamentUserIds', models.IntegerField(blank=True, default=[], verbose_name='Tournament User IDs')),
                ('tournamentGameIds', models.IntegerField(blank=True, default=[], verbose_name='Tournament Game IDs')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('userID', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('friends', models.ManyToManyField(blank=True, to='management.user')),
                ('games', models.ManyToManyField(blank=True, to='management.game')),
            ],
        ),
    ]
