var translations = {
    tr: {
        'pleaseEnterYourEmail': 'Lütfen e-posta adresinizi girin.',
        // Existing translations
        'changepassword': 'Şifre Değiştir',
        'changeusername': 'Kullanıcı Adı Değiştir',
        'uploadavatar': 'Profil Resmi Yükle',
        'totalmatches': 'Toplam Eşleşmeler',
        'win': 'Kazanma',
        'lose': 'Kaybetme',
        'nickname': 'Takma Ad',
        'email': 'E-posta',
        'username': 'Kullanıcı Adı',
        'password': 'Şifre',
        'friends': 'Arkadaşlar',
        'settings': 'Ayarlar',
        'allfriends': 'Tüm arkadaşlar',
        'user': 'Kullanıcı',
        'score': 'Puan',
        'vs': 'VS',
        'date': 'Tarih',
        // New translations
        'oldpassword': 'Eski Şifre',
        'newpassword': 'Yeni Şifre',
        'confirmpassword': 'Şifreyi Onayla',
        'changepasswordheader': 'Şifre Değiştir',
        'passwordmismatch': 'Şifreler Eşleşmiyor',
        'passwordchanged': 'Şifre Değiştirildi',
        'passwordchangefailed': 'Şifre Değiştirme Başarısız',
        'oldpasswordplaceholder': 'Eski Şifre',
        'newpasswordplaceholder': 'Yeni Şifre',
        'confirmpasswordplaceholder': 'Şifreyi Onayla',
        'typeamessageplaceholder': 'Mesaj yaz...',
        'send': 'Gönder',
        'emailauthheader': 'E-posta Doğrulama',
        'codeplaceholder': 'Kod',
        'submit': 'Gönder',
        'verificationcodesent': 'Doğrulama kodu e-postanıza gönderildi',
        'failedtosendcode': 'Doğrulama kodu gönderilemedi',
        'failedtosendcodeserver': 'Doğrulama kodu gönderilemedi. Sunucu çalışmıyor',
        'wrongcode': 'Doğrulama kodu yanlış',
        'failedtoverifyserver': 'E-posta doğrulaması başarısız. Sunucu çalışmıyor',
        'login': 'Giriş Yap',
        'signup': 'Kayıt Ol',
        'oauth': '42 Doğrulama',
        'singleplayer': 'Tek Oyunculu',
        'hi': 'Merhaba',
        'creatematch': 'Çevrimiçi oyna',
        'findmatch': 'Çevrimiçi Turnuva Oyna',
        'createtournament': 'Turnuva Oluştur',
        'findtournament': 'Turnuva Bul',
        'settingsheader': 'Ayarlar',
        'upload': 'Yükle',
        'nickname': 'Takma Ad',
        'username': 'Kullanıcı Adı',
        'email': 'E-posta',
        'savechanges': 'Değişiklikleri Kaydet',
        'deleteaccount': 'Hesabı Sil',
        'activate2fa': '2FA Aktif Et veya Devre Dışı Bırak?',
        'enabled': 'Etkin',
        'disabled': 'Devre Dışı',
        'photosuccess': 'Fotoğraf başarıyla yüklendi.',
        'photofail': 'Fotoğraf yükleme başarısız.',
        'settingssaved': 'Ayarlar kaydedildi.',
        'settingsfailed': 'Ayarlar kaydedilemedi.',
        'signupheader': 'Kayıt Ol',
        'usernameplaceholder': 'Kullanıcı Adı',
        'emailplaceholder': 'E-posta',
        'passwordplaceholder': 'Şifre',
        'confirmpasswordplaceholder': 'Şifreyi Onayla',
        'signupbtn': 'Kayıt Ol',
        'loginlink': 'Zaten hesabınız var mı?',
        'signupfailed': 'Kayıt başarısız: ',
        'passwordmismatch': 'Şifreler eşleşmiyor',
        'loginheader': 'Giriş Yap',
        'usernameplaceholder': 'Kullanıcı Adı',
        'passwordplaceholder': 'Şifre',
        'loginbtn': 'Giriş Yap',
        'forgotpassword': 'Şifremi Unuttum?',
        'registerlink': 'Hesabınız yok mu?', 
        'loginfailed': 'Giriş başarısız: ',
        'loginerror': 'Giriş sırasında bir hata oluştu.',
        'ballspeed': 'Top Hızı:',
        'ballvelocityplaceholder': 'Top Hızı',
        'totalscore': 'Toplam Skor:',
        'totalscoreplaceholder': 'Toplam Skor',
        'aidifficulty': 'AI Zorluk',
        'start': 'Başlat',
        'home': 'Ana Sayfa',
        'pause': 'Duraklat',
        'accept': 'Kabul Et',
        'reject': 'Reddet',
        'removefriend': 'Arkadaşı Sil',
        'searchfriends': 'Arkadaşları Ara',
        'search': 'Ara',
        'addfriend': 'Arkadaş Ekle',
        'friendrequests': 'Arkadaş İstekleri',
        'friends': 'Arkadaşlar',
        'addfriendheader': 'Arkadaş Ekle',
        'friendrequestsent': 'Arkadaşlık isteği gönderildi.',
        'friendrequestfailed': 'Arkadaşlık isteği gönderilemedi.',
        'friendremoved': 'Arkadaş başarıyla silindi.',
        'friendremovefailed': 'Arkadaş silme işlemi başarısız.',
        'friendrequesthandled': 'Arkadaşlık isteği başarıyla işlendi.',
        'friendrequesthandlefailed': 'Arkadaşlık isteği işleme alınamadı.',
        'prev': 'Önceki',
        'next': 'Sonraki',
        'online': 'Çevrimiçi',
        'offline': 'Çevrimdışı',
        'profile': 'Profil',
        'unblock': 'Engeli Kaldır',
        'block': 'Engelle',
        'playonline': 'Çevrimiçi Oyna',
        'playonlinetournament': 'Çevrimiçi Turnuva Oyna',
        'localgame': 'Yerel Oyun',
        'localtournament': 'Yerel Turnuva',
        'toggleSettings': 'Ayarları Aç',
        'tournamentSettingsHeader': 'Turnuva Ayarları',
        'scoreToWinLabel': 'Score To Win: ',
        'leftPaddleColorLabel': 'Sol Paddle Rengi:',
        'rightPaddleColorLabel': 'Sağ Paddle Rengi:',
        'paddleSizeLabel': 'Paddle Boyutu:',
        'paddleSizeSmall': 'Küçük',
        'paddleSizeMedium': 'Orta',
        'paddleSizeLarge': 'Büyük',
        'paddleSpeedLabel': 'Paddle Hızı:',
        'paddleSpeedSlow': 'Yavaş',
        'paddleSpeedMedium': 'Orta',
        'paddleSpeedFast': 'Hızlı',
        'ballColorLabel': 'Top Rengi:',
        'ballSpeedLabel': 'Top Hızı:',
        'ballSpeedSlow': 'Yavaş',
        'ballSpeedMedium': 'Orta',
        'ballSpeedFast': 'Hızlı',
        'ballSizeLabel': 'Top Boyutu:',
        'ballSizeSmall': 'Küçük',
        'ballSizeMedium': 'Orta',
        'ballSizeLarge': 'Büyük',
        'ballMultiplierLabel': 'Top Çarpanı: ',
        'mapThemeLabel': 'Harita Teması:',
        'mapThemeDark': 'Karanlık',
        'mapThemeLight': 'Aydınlık',
        'mapThemeForest': 'Orman',
        'mapThemeOcean': 'Okyanus',
        'mapThemeSunset': 'Günbatımı',
        'mapThemeDesert': 'Çöl',
        'mapThemePastel': 'Pastel',
        'ballTailLabel': 'Top Kuyruğu:',
        'ballTailOn': 'Açık',
        'ballTailOff': 'Kapalı',
        'cameraShakeLabel': 'Kamera Sallantısı:',
        'cameraShakeOn': 'Açık',
        'cameraShakeOff': 'Kapalı',
        'confettiLabel': 'Konfeti:',
        'confettiOn': 'Açık',
        'confettiOff': 'Kapalı',
        'startTournament': 'Turnuvayı Başlat',
        'nextMatch': 'Sıradaki Maç',
        'finishTournament': 'Turnuvayı Bitir',
        'tournamentEnded': 'Turnuva Bitti!',
        'winner': 'Kazanan: ',
        'backButton': 'Geri Dön',
        'matchIndex': 'Maç ',
        'edit': 'Düzenle',
        'save': 'Kaydet',
        'vs': 'VS',
        'nextMatchAlert': 'Sıradaki Maç:\n',
        'gameOver': 'Oyun Bitti',
        'restart': 'Yeniden Başlat',
        'closeSettings': 'Ayarları Kapat',
        'openSettings': 'Ayarları Aç',
        'loading': 'Yükleniyor...',
        'chat_sending_error': 'Kullanıcı verileri alınırken bir hata oluştu.',
        'unblock': 'Engeli Kaldır',
        'block': 'Engelle',
        'localGame': 'Yerel Oyun',
        'localTournament': 'Yerel Turnuva',
        'addopponent': 'Rakip Ekle',
        'opponentUsername': 'Rakip Kullanıcı Adı',
        'uploadImage': 'Resim Yükle',
        'removeOpponent': 'Rakip Kaldır',
        'game-over': 'Oyun Bitti',
        'UploadImage': 'Resim Yükle',
        'OpenSettings': 'Ayarları Aç',
        'StartGame': 'Oyunu Başlat',

    },
    en: {
        'opponentUsername': 'Opponent Username',
        'addopponent': 'Add Opponent',
        'localTournament': 'Local Tournament',
        // Existing translations
        'changepassword': 'Change Password',
        'changeusername': 'Change Username',
        'uploadavatar': 'Upload Profile Picture',
        'totalmatches': 'Total Matches',
        'win': 'Win',
        'lose': 'Lose',
        'nickname': 'Nickname',
        'email': 'Email',
        'username': 'Username',
        'password': 'Password',
        'friends': 'Friends',
        'settings': 'Settings',
        'allfriends': 'All friends',
        'user': 'User',
        'score': 'Score',
        'vs': 'VS',
        'date': 'Date',
        // New translations
        'oldpassword': 'Old Password',
        'newpassword': 'New Password',
        'confirmpassword': 'Confirm Password',
        'changepasswordheader': 'Change Password',
        'passwordmismatch': 'Passwords do not match',
        'passwordchanged': 'Password has been changed',
        'passwordchangefailed': 'Password change failed.',
        'oldpasswordplaceholder': 'Old Password',
        'newpasswordplaceholder': 'New Password',
        'confirmpasswordplaceholder': 'Confirm Password',
        'typeamessageplaceholder': 'Type a message...',
        'send': 'Send',
        'emailauthheader': 'Email Authentication',
        'codeplaceholder': 'Code',
        'submit': 'Submit',
        'verificationcodesent': 'Verification code sent to your email',
        'failedtosendcode': 'Failed to send verification code',
        'failedtosendcodeserver': 'Failed to send verification code. Server is not working',
        'wrongcode': 'Verification code is wrong',
        'failedtoverifyserver': 'Failed to verify email. Server is not working',
        'login': 'Login',
        'signup': 'Signup',
        'oauth': '42 Auth',
        'singleplayer': 'Single Player',
        
        'loginheader': 'Login',
        'usernameplaceholder': 'Username',
        'passwordplaceholder': 'Password',
        'loginbtn': 'Log in',
        'forgotpassword': 'Forget password?',
        'registerlink': 'Don\'t have an account?',
        'loginfailed': 'Login failed: ',
        'loginerror': 'An error occurred while logging in.',
        'hi': 'Hi',
        'creatematch': 'Play Online',
        'findmatch': 'Play Online Tournament',
        'createtournament': 'Create Tournament',
        'findtournament': 'Find Tournament',
        'settingsheader': 'Settings',
        'upload': 'Upload',
        'nickname': 'Nickname',
        'username': 'Username',
        'email': 'Email',
        'savechanges': 'Save changes',
        'deleteaccount': 'Delete account',
        'activate2fa': 'Activate or Deactivate 2FA?',
        'enabled': 'Enabled',
        'disabled': 'Disabled',
        'photosuccess': 'Photo uploaded successfully.',
        'photofail': 'Failed to upload photo.',
        'settingssaved': 'Settings have been saved.',
        'settingsfailed': 'Failed to save settings.',
        'signupheader': 'Sign Up',
        'usernameplaceholder': 'Username',
        'emailplaceholder': 'Email',
        'passwordplaceholder': 'Password',
        'confirmpasswordplaceholder': 'Confirm Password',
        'signupbtn': 'Sign Up',
        'loginlink': 'Already have an account?',
        'signupfailed': 'Signup failed: ',
        'passwordmismatch': 'Passwords do not match',
        'ballspeed': 'Ball speed:',
        'ballvelocityplaceholder': 'Ball Velocity',
        'totalscore': 'Total Score:',
        'totalscoreplaceholder': 'Total Score',
        'aidifficulty': 'AI Difficulty',
        'start': 'Start',
        'home': 'Home',
        'pause': 'Pause',
        'accept': 'Accept',
        'reject': 'Reject',
        'removefriend': 'Remove Friend',
        'searchfriends': 'Search Friends',
        'search': 'Search',
        'addfriend': 'Add Friend',
        'friendrequests': 'Friend Requests',
        'friends': 'Friends',
        'addfriendheader': 'Add Friend',
        'friendrequestsent': 'Friend request sent.',
        'friendrequestfailed': 'Failed to send friend request.',
        'friendremoved': 'Friend removed successfully.',
        'friendremovefailed': 'Failed to remove friend.',
        'friendrequesthandled': 'Friend request handled successfully.',
        'friendrequesthandlefailed': 'Failed to handle friend request.',
        'prev': 'Previous',
        'next': 'Next',
        'online': 'Online',
        'offline': 'Offline',
        'profile': 'Profile',
        'unblock': 'Unblock',
        'block': 'Block',
        'playonline': 'Play Online',
        'playonlinetournament': 'Play Online Tournament',
        'localgame': 'Local Game',
        'localtournament': 'Local Tournament',
        'toggleSettings': 'Open Settings',
        'tournamentSettingsHeader': 'Tournament Settings',
        'scoreToWinLabel': 'Score To Win: ',
        'leftPaddleColorLabel': 'Left Paddle Color:',
        'rightPaddleColorLabel': 'Right Paddle Color:',
        'paddleSizeLabel': 'Paddle Size:',
        'paddleSizeSmall': 'Small',
        'paddleSizeMedium': 'Medium',
        'paddleSizeLarge': 'Large',
        'paddleSpeedLabel': 'Paddle Speed:',
        'paddleSpeedSlow': 'Slow',
        'paddleSpeedMedium': 'Medium',
        'paddleSpeedFast': 'Fast',
        'ballColorLabel': 'Ball Color:',
        'ballSpeedLabel': 'Ball Speed:',
        'ballSpeedSlow': 'Slow',
        'ballSpeedMedium': 'Medium',
        'ballSpeedFast': 'Fast',
        'ballSizeLabel': 'Ball Size:',
        'ballSizeSmall': 'Small',
        'ballSizeMedium': 'Medium',
        'ballSizeLarge': 'Large',
        'ballMultiplierLabel': 'Ball Multiplier: ',
        'mapThemeLabel': 'Map Theme:',
        'mapThemeDark': 'Dark',
        'mapThemeLight': 'Light',
        'mapThemeForest': 'Forest',
        'mapThemeOcean': 'Ocean',
        'mapThemeSunset': 'Sunset',
        'mapThemeDesert': 'Desert',
        'mapThemePastel': 'Pastel',
        'ballTailLabel': 'Ball Tail:',
        'ballTailOn': 'On',
        'ballTailOff': 'Off',
        'cameraShakeLabel': 'Camera Shake:',
        'cameraShakeOn': 'On',
        'cameraShakeOff': 'Off',
        'confettiLabel': 'Confetti:',
        'confettiOn': 'On',
        'confettiOff': 'Off',
        'startTournament': 'Start Tournament',
        'nextMatch': 'Next Match',
        'finishTournament': 'Finish Tournament',
        'tournamentEnded': 'Tournament Ended!',
        'winner': 'Winner: ',
        'backButton': 'Back',
        'matchIndex': 'Match ',
        'edit': 'Edit',
        'save': 'Save',
        'vs': 'VS',
        'nextMatchAlert': 'Next Match:\n',
        'gameOver': 'Game Over',
        'restart': 'Restart',
        'closeSettings': 'Close Settings',
        'openSettings': 'Open Settings',
        'loading': 'Loading...',
        'chat_sending_error': 'An error occurred while fetching user data.',
        'unblock': 'Unblock',
        'block': 'Block',
        'pleaseEnterYourEmail': 'Please enter your email address.',
        'localGame': 'Local Game',
        'uploadImage': 'Upload Image',
        'removeOpponent': 'Remove Opponent',
        'game-over': 'Game Over',
        'UploadImage': 'Upload Image',
        'OpenSettings': 'Open Settings',
        'StartGame': 'Start Game',
    },
    it: {
        'removeOpponent': 'Rimuovi Avversario',
        'uploadImage': 'Carica Immagine',
        'opponentUsername': 'Nome utente avversario',
        'addopponent': 'Aggiungi Avversario',
        'localTournament': 'Torneo Locale',
        'pleaseEnterYourEmail': 'Inserisci il tuo indirizzo email.',
        // Existing translations
        'changepassword': 'Cambia la password',
        'changeusername': 'Cambia il nome utente',
        'uploadavatar': 'Carica immagine del profilo',
        'totalmatches': 'Partite totali',
        'win': 'Vincere',
        'lose': 'Perdere',
        'nickname': 'Soprannome',
        'email': 'E-mail',
        'username': 'Nome utente',
        'password': 'Password',
        'friends': 'Amici',
        'settings': 'Impostazioni',
        'allfriends': 'Tutti gli amici',
        'user': 'Utente',
        'score': 'Punteggio',
        'vs': 'VS',
        'date': 'Data',
        // New translations
        'oldpassword': 'Vecchia Password',
        'newpassword': 'Nuova Password',
        'confirmpassword': 'Conferma Password',
        'changepasswordheader': 'Cambia Password',
        'passwordmismatch': 'Le password non corrispondono',
        'passwordchanged': 'La password è stata cambiata',
        'passwordchangefailed': 'Cambio password fallito',
        'oldpasswordplaceholder': 'Vecchia Password',
        'newpasswordplaceholder': 'Nuova Password',
        'confirmpasswordplaceholder': 'Conferma Password',
        'typeamessageplaceholder': 'Scrivi un messaggio...',
        'send': 'Invia',
        'emailauthheader': 'Autenticazione Email',
        'codeplaceholder': 'Codice',
        'submit': 'Invia',
        'verificationcodesent': 'Codice di verifica inviato alla tua email',
        'failedtosendcode': 'Invio del codice di verifica fallito',
        'failedtosendcodeserver': 'Invio del codice di verifica fallito. Il server non funziona',
        'wrongcode': 'Il codice di verifica è sbagliato',
        'failedtoverifyserver': 'Verifica email fallita. Il server non funziona',
        'login': 'Accedi',
        'signup': 'Iscriviti',
        'oauth': '42 Auth',
        'singleplayer': 'Giocatore singolo',
        'loginheader': 'Accedi',
        'usernameplaceholder': 'Nome utente',
        'passwordplaceholder': 'Password',
        'loginbtn': 'Accedi',
        'forgotpassword': 'Hai dimenticato la password?',
        'registerlink': 'Non hai un account?',
        'loginfailed': 'Accesso fallito: ',
        'loginerror': 'Si è verificato un errore durante l\'accesso.',
        'hi': 'Ciao',
        'creatematch': 'giocare online',
        'findmatch': 'Gioca al torneo online',
        'createtournament': 'Crea Torneo',
        'findtournament': 'Trova Torneo',
        'settingsheader': 'Impostazioni',
        'upload': 'Carica',
        'nickname': 'Soprannome',
        'username': 'Nome utente',
        'email': 'E-mail',
        'savechanges': 'Salva modifiche',
        'deleteaccount': 'Elimina account',
        'activate2fa': 'Attivare o Disattivare 2FA?',
        'enabled': 'Abilitato',
        'disabled': 'Disabilitato',
        'photosuccess': 'Foto caricata con successo.',
        'photofail': 'Caricamento della foto fallito.',
        'settingssaved': 'Le impostazioni sono state salvate.',
        'settingsfailed': 'Salvataggio delle impostazioni fallito.',
        'signupheader': 'Iscriviti',
        'usernameplaceholder': 'Nome utente',
        'emailplaceholder': 'E-mail',
        'passwordplaceholder': 'Password',
        'confirmpasswordplaceholder': 'Conferma Password',
        'signupbtn': 'Iscriviti',
        'loginlink': 'Hai già un account?',
        'signupfailed': 'Registrazione fallita: ',
        'passwordmismatch': 'Le password non corrispondono',
        'ballspeed': 'Velocità della palla:',
        'ballvelocityplaceholder': 'Velocità della palla',
        'totalscore': 'Punteggio totale:',
        'totalscoreplaceholder': 'Punteggio totale',
        'aidifficulty': 'Difficoltà AI',
        'start': 'Inizia',
        'home': 'Home',
        'pause': 'Pausa',
        'accept': 'Accetta',
        'reject': 'Rifiuta',
        'removefriend': 'Rimuovi Amico',
        'searchfriends': 'Cerca Amici',
        'search': 'Cerca',
        'addfriend': 'Aggiungi Amico',
        'friendrequests': 'Richieste di Amicizia',
        'friends': 'Amici',
        'addfriendheader': 'Aggiungi Amico',
        'friendrequestsent': 'Richiesta di amicizia inviata.',
        'friendrequestfailed': 'Invio richiesta di amicizia fallito.',
        'friendremoved': 'Amico rimosso con successo.',
        'friendremovefailed': 'Rimozione amico fallita.',
        'friendrequesthandled': 'Richiesta di amicizia gestita con successo.',
        'friendrequesthandlefailed': 'Gestione richiesta di amicizia fallita.',
        'prev': 'Precedente',
        'next': 'Successivo',
        'online': 'Online',
        'offline': 'Offline',
        'profile': 'Profilo',
        'unblock': 'Sblocca',
        'block': 'Blocca',
        'playonline': 'Gioca Online',
        'playonlinetournament': 'Gioca al torneo online',
        'localgame': 'Gioco locale',
        'localtournament': 'Torneo locale',
        'toggleSettings': 'Apri Impostazioni',
        'tournamentSettingsHeader': 'Impostazioni del Torneo',
        'scoreToWinLabel': 'Punteggio per Vincere: ',
        'leftPaddleColorLabel': 'Colore della Paletta Sinistra:',
        'rightPaddleColorLabel': 'Colore della Paletta Destra:',
        'paddleSizeLabel': 'Dimensione della Paletta:',
        'paddleSizeSmall': 'Piccolo',
        'paddleSizeMedium': 'Medio',
        'paddleSizeLarge': 'Grande',
        'paddleSpeedLabel': 'Velocità della Paletta:',
        'paddleSpeedSlow': 'Lento',
        'paddleSpeedMedium': 'Medio',
        'paddleSpeedFast': 'Veloce',
        'ballColorLabel': 'Colore della Palla:',
        'ballSpeedLabel': 'Velocità della Palla:',
        'ballSpeedSlow': 'Lento',
        'ballSpeedMedium': 'Medio',
        'ballSpeedFast': 'Veloce',
        'ballSizeLabel': 'Dimensione della Palla:',
        'ballSizeSmall': 'Piccolo',
        'ballSizeMedium': 'Medio',
        'ballSizeLarge': 'Grande',
        'ballMultiplierLabel': 'Moltiplicatore della Palla: ',
        'mapThemeLabel': 'Tema della Mappa:',
        'mapThemeDark': 'Scuro',
        'mapThemeLight': 'Chiaro',
        'mapThemeForest': 'Foresta',
        'mapThemeOcean': 'Oceano',
        'mapThemeSunset': 'Tramonto',
        'mapThemeDesert': 'Deserto',
        'mapThemePastel': 'Pastello',
        'ballTailLabel': 'Coda della Palla:',
        'ballTailOn': 'Acceso',
        'ballTailOff': 'Spento',
        'cameraShakeLabel': 'Scuotimento della Fotocamera:',
        'cameraShakeOn': 'Acceso',
        'cameraShakeOff': 'Spento',
        'confettiLabel': 'Coriandoli:',
        'confettiOn': 'Acceso',
        'confettiOff': 'Spento',
        'startTournament': 'Inizia il Torneo',
        'nextMatch': 'Prossimo Match',
        'finishTournament': 'Termina il Torneo',
        'tournamentEnded': 'Torneo Finito!',
        'winner': 'Vincitore: ',
        'backButton': 'Indietro',
        'matchIndex': 'Match ',
        'edit': 'Modifica',
        'save': 'Salva',
        'vs': 'VS',
        'nextMatchAlert': 'Prossimo Match:\n',
        'gameOver': 'Game Over',
        'restart': 'Ricomincia',
        'closeSettings': 'Chiudi Impostazioni',
        'openSettings': 'Apri Impostazioni',  
        'loading': 'Caricamento...',
        'chat_sending_error': 'Si è verificato un errore durante il recupero dei dati utente.',
        'unblock': 'Sblocca',
        'block': 'Blocca',
        'localGame': 'Gioco Locale',
        'game-over': 'Game Over',
        'UploadImage': 'Carica Immagine',
        'OpenSettings': 'Apri Imp',
        'StartGame': 'Inizia il gioco',
    }
};

function getWord(word) {
    let language = localStorage.getItem('selectedLanguage');
    return translations[language][word];
}


function changeLanguage() {
    let language = localStorage.getItem('selectedLanguage');
    document.querySelectorAll('[translate-id]').forEach(function(element) {
        var key = element.getAttribute('translate-id');
        if (element.placeholder !== undefined) {
            element.placeholder = translations[language][key];
        } else {
            element.textContent = translations[language][key];
        }
    });
    checkImgJs()
}

function language(language) {
    localStorage.setItem('selectedLanguage', language);
    changeLanguage();
}
